### ISSUE TITLE
Not getting permission popup & no response from plugin

### ISSUE THREAD

**Issue by akashjain12366** [xUnholy/cordova-device-accounts-v2#1]
Hello,
I have used this plugin in my ionic 3 project using https://ionicframework.com/docs/native/device-accounts/
But When I run app I don't receive any permission popup for accessing device accounts. Also, I am not getting a response from plugin neither success nor error. Can you please help?

**Comment by xunholy** [comment]
Hi, that's because the one you've used is not being maintained and doesn't work with the latest version of Android - I would suggest using my updated version or at least updating those things I've updated to get the functionality you're after.

If you have any further questions let me know!

**Comment by xunholy** [comment]
@akashjain12366 if this solves your issue please let me know, I'll be closing this issue within the next 24hours.
