### ISSUE TITLE
getPermissions does not resolve/reject 

### ISSUE THREAD

**Issue by endareBrock** [xUnholy/cordova-device-accounts-v2#10]
Under Android 8.0 the plugin does work fine.
But i need to retrieve a non google account which is not an option by .getPermissions.

My flow is as follows->
androidPermissions.getPermissions => deviceAccounts.getPermissions => deviceAccounts.getByType. All functions are promises but the deviceAccounts.getPermissions does not resolve or reject. thus never firing the getByType.

The deviceAccounts.getPermissions does give me a popup with Google accounts but not any others. When selecting a google account and confirming it. No callback is being fired.

< 8.0.0 works fine

**Comment by xunholy** [comment]
Interesting. I'll have a look in the morning If I get a spare minute or two, feel free to fork and try debug or improve yourself, always happy to have more people contribute

**Comment by endareBrock** [comment]
I think the 'only google' is straightforward 
![image](https://user-images.githubusercontent.com/25737301/58179828-3ca0d000-7ca9-11e9-9b03-78c163cc881a.png)

android api says:
`an optional string array of account types.`, i think leaving the 'com.google' out will give all the options 


The not returning problem is maybe related to the fact there is no return value ? and the other methods do.

**Comment by endareBrock** [comment]
Can confirm that replacing new String[]{"com.google"} by null, lets you choose between all your accounts. Right now i am struggling with the second issue

**Comment by endareBrock** [comment]
I almost figured it out.
You need to set the callbackContext locally and do following

```
  private void getPermissions() {
    AccountManager manager = AccountManager.get(cordova.getActivity().getApplicationContext());
    Intent accountIntent = manager.newChooseAccountIntent(null, null, null, null, null, null, null);
    cordova.setActivityResultCallback(this);
    cordova.getActivity().startActivityForResult(accountIntent, VISIBILITY_VISIBLE);
  }

  @Override
  public void onActivityResult(int requestCode, int resultCode, Intent intent){
    if(requestCode == VISIBILITY_VISIBLE && this.callbackContext != null){
        this.callbackContext.success("Success");
    } else {
        this.callbackContext.error("Invalid requestCode: " + requestCode);
    }
  }
```
It fires the success callback but reaches the reject of the app.

**Comment by endareBrock** [comment]
i managed to write this but it still needs improvements. 
Would you mind taking a look ? My Android knowledge is far, far away.
```
  private void getPermissions(String type) {
    AccountManager manager = AccountManager.get(cordova.getActivity().getApplicationContext());
    Intent accountIntent = manager.newChooseAccountIntent(null, null, new String[]{type}, null, null, null, null);
    cordova.setActivityResultCallback(this);
    cordova.getActivity().startActivityForResult(accountIntent, VISIBILITY_VISIBLE);
  }
  private void getPermissions() {
      AccountManager manager = AccountManager.get(cordova.getActivity().getApplicationContext());
      Intent accountIntent = manager.newChooseAccountIntent(null, null, null, null, null, null, null);
      cordova.setActivityResultCallback(this);
      cordova.getActivity().startActivityForResult(accountIntent, VISIBILITY_VISIBLE);
    }

  @Override
  public void onActivityResult(int requestCode, int resultCode, Intent data){
    if(requestCode == VISIBILITY_VISIBLE && this.callbackContext != null){
         this.callbackContext.success("Success " + data.getStringExtra(AccountManager.KEY_ACCOUNT_TYPE +" "+ data.getStringExtra(AccountManager.KEY_ACCOUNT_NAME)));
    } else {
         this.callbackContext.error("Invalid requestCode: " + requestCode);
    }
  }
``` 
This would have the option to give a type argument (instead of the "google.com")
![image](https://user-images.githubusercontent.com/25737301/58207572-3cbdc180-7ce3-11e9-9f26-3ef0128c8891.png)

**Comment by xunholy** [comment]
Separating the account type and callback issues https://github.com/xUnholy/cordova-device-accounts/issues/11

**Comment by xunholy** [comment]
This would be much easier to review in a pull request - additionally, I think the getPermissions() function should actually return all accounts, then the type should be handled by the getAccounts() function which already handles the type to receive.

**Comment by xunholy** [comment]
I've been working on making an easy usage guide for this plugin with an ionic application. Check it out here, perhaps we can add this to the examples once we also get this working. https://github.com/xUnholy/cordova-device-accounts-example

**Comment by xunholy** [comment]
Please review and test the following - I've used some of your logic and tweaked it to solve the underlying issue with the promise resolving incorrectly which was a bug. Effectively the promise would be rejected even though internally it resolved.

**Comment by xunholy** [comment]
Pull request can be reviewed here - https://github.com/xUnholy/cordova-device-accounts/pull/12
