### ISSUE TITLE
getPermissions() does not return all account types

### ISSUE THREAD

**Issue by xunholy** [xUnholy/cordova-device-accounts-v2#11]
Should request all account types on the device, currently only returns `new String[]{"com.google"}`

**Comment by xunholy** [comment]
Need to decide if this should be returning ALL accounts regardless if they're emails or not. 

EG. This will return `com.*` accounts which do not follow a regular format, and other domains where they use an internal account set up that is an arbitrary naming convention.

**Comment by endareBrock** [comment]
I think this would be a good added value.
In my case i need to pick a certain account ( not com.*) and if not, do nothing.
com.* or com.google still limits the dynamic of the plugin and forces more forks for custom types.

**Comment by endareBrock** [comment]
The request permissions will only give you access to 1 (the selected account). 
For my project i would need to request a certain custom account and only retrieve that one.
Only allowing com.* renders this impossible.
The get by type is not useful when there is only permission given for com.google.
(EG. i cannot retrieve my account with type X if i only give permission to a single com.* account)

**Comment by xunholy** [comment]
I agree, it's probably a good idea to default to com.google however allow a type to be defined in the request. If you would like to make these changes on your fork I'm happy for you to raise a PR and contribute, or I can also look into it when I get some more time later tonight.

**Comment by endareBrock** [comment]
https://github.com/xUnholy/cordova-device-accounts/pull/13
I cant find where to edit the typing file :
```
    /**
     *  Get permissions for access to email registered on Android device 8.0+
     * @returns {Promise<string>}
     */
    getPermissions(type?: string): Promise<string>;
```

**Comment by xunholy** [comment]
https://github.com/xUnholy/ionic-native/blob/master/src/%40ionic-native/plugins/device-accounts/index.ts

I believe it should be auto-generated and it will use the declared documentation fields above the function?

**Comment by endareBrock** [comment]
It is possible, else we just need to add `  * @param {string} type`

**Comment by xunholy** [comment]
Completed 

https://github.com/xUnholy/cordova-device-accounts-v2/commit/f7fe66b89961dd6910ca3c82871749f7a7893fd7

https://github.com/ionic-team/ionic-native/pull/3048
