### ISSUE TITLE
get() returns empty array in Android 10

### ISSUE THREAD

**Issue by Pigsnuck** [xUnholy/cordova-device-accounts-v2#15]
get() is returning an empty array on my Android 10 device, although it returns a list of accounts on an Android 6.0.1 test device.

In AndroidManifest.xml, I have set the following permissions:
GET_ACCOUNTS
GET_ACCOUNTS_PRIVILEGED

Ominously, Android Studio underlines the GET_ACCOUNTS_PRIVILEGED line with the message "Permission is only granted to system apps".  Is this feature no longer supported since some version of Android, or is there a workaround?

See: https://stackoverflow.com/questions/53989497/ionic-4-cordova-get-device-accounts

**Comment by xunholy** [comment]
Thanks @Pigsnuck what version are you using of the plugin and ionic native?

**Comment by Pigsnuck** [comment]
Hi @xUnholy ,

I am not using Ionic, just plain old Cordova:

Cordova version: 9.0.0
Plugin version: 2.0.8

**Comment by xunholy** [comment]
@Pigsnuck

Can you please try using getPermission()  instead of regular get() and let me know if that solves your issue.

This definitely sounds like a permission issue perhaps however I'd be interested to see if that function helps.

**Comment by acedigibits** [comment]
i have set android.permission.GET_ACCOUNTS and android.permission.GET_ACCOUNTS_PRIVILEGED in manifest and also granted in app. i am getting no response in get() ,

on getPermissions() it shows list of emails but when i select one i only get success as message in callback (need email id that user selected).

getEmails() gives error 

"Error in Success callbackId: Permission1989722990 : TypeError: DeviceAccounts.getByType is not a function"

**Comment by Pigsnuck** [comment]
Hi @xUnholy ,

When calling getPermissions(), a dialog pops up asking which account I want to use (I only have 1 account on this test device). I select the account and getPermissions() returns a single string "SUCCESS" in the respose.

getPermissions() is unfortunately not an option for me, because I need to iterate ALL the accounts.

**Comment by xunholy** [comment]
So since Android 8.0.0 you can't iterate through all accounts without the user first giving permissions to have the app be given permission to that account.

So your application should call getPermission() this will ensure the application can now view the single or multiple accounts that have been selected by the user.

Once the have accepted the accounts you can then call the get() function which will contain the array of emails that the application can view.

**Comment by Pigsnuck** [comment]
I just tried calling getPermission() before get() and I can confirm that this does indeed work.

For others experiencing this, I changed my logic to: call get(), if the accounts list is empty, call getPermissions(), which will cause Android to display a dialog so the user can select the appropriate account. Then the email addresses can be processed as usual.

**Comment by betonlineph** [comment]
i have a multiple emails on my android device i already get all those emails on get() the problem is how will i know which email being selected?

**Comment by Pigsnuck** [comment]
I think your Android device is running an older version of the OS if it's returning multiple emails?  If so, then you need to assume it could be ANY or ALL of those email addresses.
