### ISSUE TITLE
Get Accounts returning Empty array

### ISSUE THREAD

**Issue by vishwas097** [xUnholy/cordova-device-accounts-v2#17]
In android version 10 get Account returning an empty array, but other versions which are less than 10 returning accounts. Is any workaround or solution available for this issue?

**Comment by xunholy** [comment]
Which method are you currently using? https://github.com/xUnholy/cordova-device-accounts-v2#methods

Are you appropriately getting access to the device accounts? 

```
Note: since Android 8.0.0+ device accounts are not visible to the application. Users must grant access to email accounts they wish to be visible to the application.
```

**Comment by vishwas097** [comment]
Ok, thanks. I am able to get Accounts now.  Is there any way to forcefully get permission from the user? Or any way to hide the cancel button so that the user must select his email account. Is there any workaround for this? If yes please let me know. Thankyou.
